### 1. A matriz de dispersão S obtida de uma certa base de dados (standardizada e centrada na média 0) é 
S = np.matrix( [  
    [ 97.18075394 , 4.01869602 , 77.40991318],  
    [ 4.01869602 ,108.87624652 , 8.93428697],  
    [ 77.40991318 , 8.93428697 , 98.049557675]  
]) 

In [30]:
import numpy as np
import numpy.linalg as linalg

In [31]:
S = np.matrix([
    [97.18075394 , 4.01869602 , 77.40991318],
    [4.01869602 ,108.87624652 , 8.93428697],
    [77.40991318 , 8.93428697 , 98.049557675]
])
S

matrix([[ 97.18075394,   4.01869602,  77.40991318],
        [  4.01869602, 108.87624652,   8.93428697],
        [ 77.40991318,   8.93428697,  98.04955768]])

##### (a) Calcule as componentes principais.  

In [42]:
# sigma = valores singulares
e_faces, sigma, principal_components_T = linalg.svd(S.transpose(), full_matrices=False)
e_values = sigma*sigma
trace = sum(e_values)

e_values = e_values/trace
print(e_values)

principal_components_T.transpose()

[0.72114294 0.2695095  0.00934756]


matrix([[-0.69655167,  0.12282659, -0.70691542],
        [-0.13494668, -0.99008273, -0.03905863],
        [-0.70470219,  0.06818953,  0.70621882]])

##### (b) Indique as componentes principais que preservam cerca de 90% da informação. Calcule a projeção do array([0.09710545, 2.18567601, 0.0364491]) sobre o espaço gerado por estas componentes principais.

In [33]:
# resposta à 1ª parte da 1. b)
principal_components_90 = principal_components_T[0:2]
print("Componentes principais que preservam 90%:\n", principal_components_90, "\n")

# resposta à 2ª parte da 1. b)
input_vector = np.matrix([0.09710545, 2.18567601, 0.0364491])
projection = np.dot(input_vector, principal_components_90.T)
print("Projeção dos dados:", projection)

Componentes principais que preservam 90%:
 [[-0.69655167 -0.13494668 -0.70470219]
 [ 0.12282659 -0.99008273  0.06818953]] 

Projeção dos dados: [[-0.38827444 -2.1495875 ]]


### Resposta do ChatGPT

In [34]:
import numpy as np

# Dada matriz
S = np.array([
    [97.18075394, 4.01869602, 77.40991318],
    [4.01869602, 108.87624652, 8.93428697],
    [77.40991318, 8.93428697, 98.049557675]
])

# Realize a Decomposição SVD
U, Sigma, Vt = np.linalg.svd(S)
# Calcule a proporção cumulativa dos quadrados dos valores singulares
cumulative_ratio = np.cumsum(Sigma**2) / np.sum(Sigma**2)

# Encontre o número de componentes necessárias para preservar cerca de 90% da informação
num_components = np.argmax(cumulative_ratio >= 0.9) + 1

# Mantenha apenas as primeiras 'num_components' componentes principais
principal_components_90_percent = Vt[:num_components, :]

# Projeção do vetor [0.09710545, 2.18567601, 0.0364491] no espaço gerado pelas componentes principais
input_vector = np.array([0.09710545, 2.18567601, 0.0364491])
projection = np.dot(input_vector, principal_components_90_percent.T)

# Imprima os resultados
print("Número de componentes para preservar 90% da informação:", num_components)
print("\nComponentes Principais (para 90% de preservação):")
print(principal_components_90_percent)
print("\nProjeção do vetor de entrada:")
print(projection)

Número de componentes para preservar 90% da informação: 2

Componentes Principais (para 90% de preservação):
[[-0.69655167 -0.13494668 -0.70470219]
 [ 0.12282659 -0.99008273  0.06818953]]

Projeção do vetor de entrada:
[-0.38827444 -2.1495875 ]
